<a href="https://colab.research.google.com/github/ekansh2112/woc4.0-ml-sentiment-analysis-ekanshgupta/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


# **Loading Numpy**

In [ ]:
import numpy as np

# **The Basics**

In [ ]:
a = np.array([1,2,3],dtype='int32')

In [ ]:
b = np.array([[9.0,8.0,7.0],[1.2,2.1,3.2]])
print(b)

[[9.  8.  7. ]
 [1.2 2.1 3.2]]


In [ ]:
#Get Dimension
a.ndim

1

In [ ]:
#Get Shape
b.shape

(2, 3)

In [ ]:
#Get Type
a.dtype

dtype('int16')

In [ ]:
#Get Size
b.itemsize

8

In [ ]:
# Get Total Size
b.nbytes

48

# **Accessing/Changing specific elements, rows, columns,etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element
a[1,-2]

13

In [ ]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#[row,startIndex:endIndex:stepSize]
a[0,1:6:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2] = 5
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# **Initializing different types of arrays**

In [ ]:
#All zeros matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
#Any other number full like
np.full_like(a,4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#random decimal numbers
np.random.rand(4,2)

array([[0.79480216, 0.13705617],
       [0.93070117, 0.16483725],
       [0.39693969, 0.30818985],
       [0.49810649, 0.96261796]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.45575006, 0.21513249, 0.26844994, 0.37863553, 0.72607861,
        0.13638199, 0.67749421],
       [0.97771004, 0.27150366, 0.78319773, 0.86763379, 0.83090803,
        0.86265438, 0.68653633]])

In [ ]:
#random integer values
np.random.randint(-4,7,size=(3,3))

array([[-3, -4,  3],
       [ 4,  5, -2],
       [ 2, -2, -3]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
b

array([100,   2,   3])

# **Mathematics**

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a+=2
a

array([3, 4, 5, 6])

In [ ]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [ ]:
a ** 2

array([ 9, 16, 25, 36])

In [ ]:
np.sin(a) #sine

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [ ]:
np.cos(a) #cosine

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# **Linear Algebra**

In [ ]:
#Multiplication
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b) #matrix multiplicaiton

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#find the determinant
c = np.identity(3)
np.linalg.det(c) #linalg-linear algebra, det - determinant

1.0

## **Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats,axis=0)

array([1, 2, 3])

In [ ]:
np.max(stats,axis=1)

array([3, 6])

In [ ]:
np.sum(stats,axis=1)

array([ 6, 15])

# **Reorganizing arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
#horizonal stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack([v1,v2,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4])

# **Miscellaneous**

**Load Data from File**

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
filedata = np.genfromtxt('/content/gdrive/Othercomputers/My Laptop/DAIICT/MSTC_WOC/temp.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

**Boolean Masking and Advanced Indexing**

In [ ]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
#You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
~((filedata>50) & (filedata<100)) #not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])